name: 'Setup Bun and Dependencies'
description: 'Installs Bun and project dependencies'
runs:
  using: "composite"
  steps:
    - name: Install Bun
      uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      run: bun install --frozen-lockfile
      shell: bash
