name: CI/CD Pipeline

# Default permissions for all jobs (principle of least privilege)
# Most jobs only need to read repository contents
permissions:
  contents: read    # Required to checkout repository

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      force_release:
        description: 'Force a release even if no changes detected'
        required: false
        default: false
        type: boolean

# Ensure only one workflow runs at a time for the same ref
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '20'
  BUN_VERSION: 'latest'

jobs:
  # Stage 1: Code Quality & Fast Tests
  lint-and-typecheck:
    name: 🔍 Lint & Type Check
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Only needs to read repository contents
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run ESLint
        run: bun run lint

      - name: Run TypeScript check
        run: bun run typecheck

  # Stage 2: SQLite Tests (Fastest)
  test-sqlite:
    name: 🗄️ SQLite Tests
    runs-on: ubuntu-latest
    needs: lint-and-typecheck
    permissions:
      contents: read  # Only needs to read repository contents
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Setup SQLite database
        env:
          NODE_ENV: test
          DB_TYPE: sqlite
          SQLITE_DB_PATH: ./tests/e2e/test_database.sqlite
        run: |
          mkdir -p ./tests/e2e
          bun run db:migrate:sqlite || echo "Migration failed but continuing"

      - name: Run SQLite tests
        env:
          NODE_ENV: test
          DB_TYPE: sqlite
          SQLITE_DB_PATH: ./tests/e2e/test_database.sqlite
        run: bun test --coverage

      - name: Upload SQLite coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-sqlite
          path: ./coverage

  # Stage 3: PostgreSQL Tests
  test-postgresql:
    name: 🐘 PostgreSQL Tests
    runs-on: ubuntu-latest
    needs: test-sqlite
    permissions:
      contents: read  # Only needs to read repository contents
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: openbadges_test
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5433 -U testuser -d openbadges_test; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
          echo "PostgreSQL is ready."
        timeout-minutes: 1

      - name: Run PostgreSQL migrations
        env:
          NODE_ENV: test
          DB_TYPE: postgresql
          DATABASE_URL: postgres://testuser:testpassword@localhost:5433/openbadges_test
        run: bun run db:migrate:pg

      - name: Run PostgreSQL tests
        env:
          NODE_ENV: test
          DB_TYPE: postgresql
          DATABASE_URL: postgres://testuser:testpassword@localhost:5433/openbadges_test
        run: bun test --coverage

      - name: Upload PostgreSQL coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-postgresql
          path: ./coverage

  # Stage 4: End-to-End Tests
  test-e2e:
    name: 🧪 E2E Tests
    runs-on: ubuntu-latest
    needs: test-postgresql
    permissions:
      contents: read  # Only needs to read repository contents
    strategy:
      matrix:
        database: [sqlite, postgresql]
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: openbadges_test
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Setup database (SQLite)
        if: matrix.database == 'sqlite'
        run: |
          mkdir -p ./tests/e2e
          # Use the same migration logic as local E2E tests
          # This ensures the 0001_cool_martin_li.sql migration with custom breakpoints is applied correctly
          bun run test:e2e:sqlite

      - name: Setup database (PostgreSQL)
        if: matrix.database == 'postgresql'
        run: |
          until pg_isready -h localhost -p 5433 -U testuser -d openbadges_test; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
          bun run test:e2e:pg

      - name: Upload E2E test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-results-${{ matrix.database }}
          path: ./test-results-*.xml

  # Stage 5: Build Application
  build:
    name: 🏗️ Build Application
    runs-on: ubuntu-latest
    needs: test-e2e
    permissions:
      contents: read  # Only needs to read repository contents
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build application
        run: bun run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/
            package.json

  # Stage 6: Release (Main branch only)
  release:
    name: 🚀 Release
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: write         # Required to create releases and push tags
      issues: write          # Required to comment on issues for release notes
      pull-requests: write   # Required to comment on PRs for release notes
      packages: write        # Required if publishing packages
      id-token: write        # Required for OIDC token for secure operations
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}

    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          # Use GitHub App token for checkout to prevent lingering GITHUB_TOKEN headers
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Mask GitHub App token
        run: echo "::add-mask::${{ steps.app-token.outputs.token }}"

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Configure git to use GitHub App token for authentication via HTTP header (more secure)
          git remote set-url origin "https://github.com/${{ github.repository }}.git"
          git config --global http.https://github.com/.extraheader "Authorization: Bearer ${{ steps.app-token.outputs.token }}"

      - name: Relax branch protection for release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          echo "Disabling strict status checks to allow release commits"
          # NOTE: Status check names must match the job names in this workflow
          # Keep in sync with job labels: "🔍 Lint & Type Check", "🗄️ SQLite Tests", "🐘 PostgreSQL Tests", "🏗️ Build Application"
          cat > branch_protection.json << 'EOF'
          {
            "required_status_checks": {
              "strict": false,
              "contexts": ["🔍 Lint & Type Check", "🗄️ SQLite Tests", "🐘 PostgreSQL Tests", "🏗️ Build Application"]
            },
            "enforce_admins": false,
            "required_pull_request_reviews": {
              "required_approving_review_count": 1,
              "dismiss_stale_reviews": true,
              "require_code_owner_reviews": false
            },
            "restrictions": null
          }
          EOF
          gh api --method PUT repos/${{ github.repository }}/branches/main/protection --input branch_protection.json
          rm branch_protection.json

      - name: Release
        id: semantic
        env:
          # Use GitHub App token for semantic-release - bypasses branch protection for release commits
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          NPM_TOKEN: dummy
        run: |
          set -euo pipefail  # Exit on error, undefined vars, pipe failures

          echo "Starting semantic-release process..."
          echo "Branch: ${{ github.ref_name }}"
          echo "Event: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"

          # Debug git configuration
          echo "Git configuration:"
          git config --list | grep -E "user\." || true
          echo "Git remote configuration:"
          git remote -v | sed 's/x-access-token:[^@]*@/x-access-token:***@/g' || true
          echo "Testing git authentication:"
          git ls-remote origin HEAD || echo "Git authentication test failed"

          # Check if we have commits to release
          echo "Recent commits:"
          git log --oneline -5 || true

          # Check for releasable commits since last tag
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -n "$LAST_TAG" ]; then
            echo "Last tag: $LAST_TAG"
            echo "Commits since last tag:"
            git log --oneline "$LAST_TAG"..HEAD || true
          else
            echo "No previous tags found"
          fi

          # Check semantic-release configuration
          echo "Semantic-release configuration:"
          cat .releaserc.json || echo "No .releaserc.json found"

          # Create .npmrc to prevent npm publishing issues
          echo "//registry.npmjs.org/:_authToken=dummy" > .npmrc

          # Run semantic-release and capture output
          echo "Running semantic-release..."
          
          # Store the git tag before semantic-release
          BEFORE_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          
          if ! bun run semantic-release; then
            echo "ERROR: semantic-release failed"
            echo "Check the logs above for details"
            exit 1
          fi
          
          # Check if a new tag was created
          AFTER_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          
          if [ "$BEFORE_TAG" != "$AFTER_TAG" ] && [ -n "$AFTER_TAG" ]; then
            echo "New release published: $AFTER_TAG"
            echo "new_release_published=true" >> $GITHUB_OUTPUT
            echo "new_release_version=$AFTER_TAG" >> $GITHUB_OUTPUT
          else
            echo "No new release published"
            echo "new_release_published=false" >> $GITHUB_OUTPUT
            echo "new_release_version=" >> $GITHUB_OUTPUT
          fi

          echo "Release process completed successfully"

      - name: Restore branch protection
        if: always()  # Run even if previous steps failed
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          echo "Restoring strict status checks for branch protection"
          # NOTE: Status check names must match the job names in this workflow  
          # Keep in sync with job labels: "🔍 Lint & Type Check", "🗄️ SQLite Tests", "🐘 PostgreSQL Tests", "🏗️ Build Application"
          cat > branch_protection.json << 'EOF'
          {
            "required_status_checks": {
              "strict": true,
              "contexts": ["🔍 Lint & Type Check", "🗄️ SQLite Tests", "🐘 PostgreSQL Tests", "🏗️ Build Application"]
            },
            "enforce_admins": false,
            "required_pull_request_reviews": {
              "required_approving_review_count": 1,
              "dismiss_stale_reviews": true,
              "require_code_owner_reviews": false
            },
            "restrictions": null
          }
          EOF
          gh api --method PUT repos/${{ github.repository }}/branches/main/protection --input branch_protection.json || echo "Failed to restore branch protection - manual intervention may be required"
          rm -f branch_protection.json

  # Stage 7: Docker Build & Push (After successful release)
  docker:
    name: 🐳 Docker Build & Push
    runs-on: ubuntu-latest
    needs: release
    if: needs.release.outputs.new_release_published == 'true'
    permissions:
      contents: read    # Required to checkout repository
      packages: write   # Required to publish Docker images to GitHub Container Registry
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: 'arm64,amd64'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # Using GITHUB_TOKEN for container registry authentication
          # This is the standard approach for GHCR and doesn't require a PAT
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},value=${{ needs.release.outputs.new_release_version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ needs.release.outputs.new_release_version }}
            type=semver,pattern={{major}},value=${{ needs.release.outputs.new_release_version }}
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify multi-architecture build
        run: |
          FIRST_TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n 1)
          echo "Verifying architectures for: $FIRST_TAG"
          # Wait for manifest to be available
          for i in {1..5}; do
            if docker manifest inspect $FIRST_TAG > /dev/null 2>&1; then
              break
            fi
            echo "Waiting for manifest... ($i/5)"
            sleep 10
          done

          # Verify architectures
          MANIFEST=$(docker manifest inspect $FIRST_TAG)
          echo "$MANIFEST"
          if echo "$MANIFEST" | grep -q "amd64" && echo "$MANIFEST" | grep -q "arm64"; then
            echo "✅ Multi-architecture build verified"
          else
            echo "❌ Multi-architecture build failed"
            exit 1
          fi
