name: Release

on:
  workflow_dispatch:
  # Disabled automatic triggers to prevent conflicts with main.yml
  # push:
  #   branches:
  #     - main
  #     - beta
  #   paths-ignore:
  #     - 'docs/**'
  #     - '*.md'
  #     - '.augment/**'
  # workflow_run:
  #   workflows: ["CI"]
  #   types:
  #     - completed

env:
  GH_PAT: ${{ secrets.ORG_RELEASE_PAT }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          # Security: For workflow_run events, always checkout the default branch HEAD
          # to prevent execution of untrusted code from pull requests
          ref: ${{ github.event_name == 'workflow_run' && 'main' || github.sha }}
          fetch-depth: 0
          # A PAT is required here to allow this workflow to trigger the Docker workflow.
          # The default GITHUB_TOKEN does not have sufficient permissions.
          # Using organization-level secret for better security and management.
          token: ${{ secrets.ORG_RELEASE_PAT }}
          persist-credentials: false

      - uses: ./.github/actions/setup-bun

      - name: Release with semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_RELEASE_PAT }}
          NPM_TOKEN: dummy  # Not publishing to NPM, only creating GitHub releases
        run: |
          set -euo pipefail  # Exit on error, undefined vars, pipe failures

          echo "Starting semantic-release process..."
          echo "Branch: ${{ github.ref_name }}"
          echo "Event: ${{ github.event_name }}"

          if ! bun run semantic-release; then
            echo "ERROR: semantic-release failed"
            echo "Check the logs above for details"
            exit 1
          fi

          echo "Release process completed successfully"
