name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun run lint

  test-core:
    name: Core Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run core tests
        run: bun run test:core

      - name: Run unit tests
        run: bun run test:unit

  test-sqlite:
    name: SQLite Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run SQLite integration tests
        run: bun run test:integration:sqlite

      - name: Run E2E tests with SQLite
        run: bun run test:e2e:sqlite

  test-postgresql:
    name: PostgreSQL Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: openbadges_test
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run PostgreSQL integration tests
        run: bun run test:integration:pg
        env:
          DB_TYPE: postgresql
          DATABASE_URL: postgresql://testuser:testpassword@localhost:5433/openbadges_test
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5433
          POSTGRES_DB: openbadges_test

      - name: Run E2E tests with PostgreSQL
        run: bun run test:e2e:pg
        env:
          DB_TYPE: postgresql
          DATABASE_URL: postgresql://testuser:testpassword@localhost:5433/openbadges_test
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5433
          POSTGRES_DB: openbadges_test

  test-containers:
    name: Test Containers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run E2E tests with Test Containers
        run: bun run test:e2e:containers
        env:
          DB_TYPE: postgresql
          USE_TEST_CONTAINERS: true

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test-core, test-sqlite, test-postgresql, test-containers]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/
