name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

# Limit permissions of the GITHUB_TOKEN
permissions:
  contents: read
  security-events: write # Required for CodeQL

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun run lint

  test-core:
    name: Core Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run core tests
        run: bun run test:core
        env:
          NODE_PATH: "."

      - name: Run unit tests
        run: bun run test:unit
        env:
          NODE_PATH: "."
          NODE_ENV: test
          AUTH_DISABLE_RBAC: true
          AUTH_API_KEY_TEST: verysecretkeye2e:test-user:E2E Test API Key
          DB_TYPE: sqlite
          SQLITE_FILE: ":memory:"

  test-sqlite:
    name: SQLite Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Create SQLite directory and set permissions
        run: |
          mkdir -p tests/e2e
          touch tests/e2e/test_database.sqlite
          chmod 777 tests/e2e/test_database.sqlite
          chmod 777 tests/e2e

      - name: Run SQLite integration tests
        run: bun run test:integration:sqlite
        env:
          NODE_PATH: "."
          NODE_ENV: test
          AUTH_DISABLE_RBAC: true
          AUTH_API_KEY_TEST: verysecretkeye2e:test-user:E2E Test API Key
          DB_TYPE: sqlite
          SQLITE_FILE: ":memory:"

      - name: Run E2E tests with SQLite
        run: bun run test:e2e:sqlite
        env:
          NODE_PATH: "."
          NODE_ENV: test
          AUTH_DISABLE_RBAC: true
          AUTH_API_KEY_TEST: verysecretkeye2e:test-user:E2E Test API Key
          DB_TYPE: sqlite
          SQLITE_FILE: "./tests/e2e/test_database.sqlite"

  test-postgresql:
    name: PostgreSQL Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: openbadges_test
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Create SQLite directory and set permissions
        run: |
          mkdir -p tests/e2e
          touch tests/e2e/test_database.sqlite
          chmod 777 tests/e2e/test_database.sqlite
          chmod 777 tests/e2e

      - name: Run PostgreSQL integration tests
        run: bun run test:integration:pg
        env:
          NODE_PATH: "."
          NODE_ENV: test
          AUTH_DISABLE_RBAC: true
          AUTH_API_KEY_TEST: verysecretkeye2e:test-user:E2E Test API Key
          DB_TYPE: postgresql
          DATABASE_URL: postgresql://testuser:testpassword@localhost:5433/openbadges_test
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5433
          POSTGRES_DB: openbadges_test

      - name: Run E2E tests with PostgreSQL
        run: bun run test:e2e:pg
        env:
          NODE_PATH: "."
          NODE_ENV: test
          AUTH_DISABLE_RBAC: true
          AUTH_API_KEY_TEST: verysecretkeye2e:test-user:E2E Test API Key
          DB_TYPE: postgresql
          DATABASE_URL: postgresql://testuser:testpassword@localhost:5433/openbadges_test
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5433
          POSTGRES_DB: openbadges_test

  test-containers:
    name: Test Containers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Install testcontainers
        run: bun add -d testcontainers

      - name: Create SQLite directory and set permissions
        run: |
          mkdir -p tests/e2e
          touch tests/e2e/test_database.sqlite
          chmod 777 tests/e2e/test_database.sqlite
          chmod 777 tests/e2e

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Start Docker service
        run: sudo systemctl start docker

      - name: Run E2E tests with Test Containers
        run: bun run test:e2e:containers
        env:
          NODE_PATH: "."
          NODE_ENV: test
          AUTH_DISABLE_RBAC: true
          AUTH_API_KEY_TEST: verysecretkeye2e:test-user:E2E Test API Key
          DB_TYPE: postgresql
          USE_TEST_CONTAINERS: true

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test-core, test-sqlite, test-postgresql, test-containers]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/
